hash-format = "sha256"

[[files]]
file = "config/capes.json5"

[[files]]
file = "config/craftpresence.json"

[[files]]
file = "config/defaultoptions/keybindings.txt"

[[files]]
file = "config/defaultoptions/options.txt"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"

[[files]]
file = "config/isxander-main-menu-credits.json"

[[files]]
file = "config/replaymod.json"

[[files]]
file = "config/roughlyenoughitems/config.json5"

[[files]]
file = "config/visuality.json"

[[files]]
file = "config/waila/waila.json"

[[files]]
file = "config/waila/waila_plugins.json"

[[files]]
file = "config/xaerominimap.txt"

[[files]]
file = "config/xaerominimap_entities.json"

[[files]]
file = "config/xaeropatreon.txt"

[[files]]
file = "config/xaeroworldmap.txt"

[[files]]
file = "config/zoomify.json"

[[files]]
file = "credits.txt"

[[files]]
file = "icon.png"

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
metafile = true

[[files]]
file = "mods/worldeditcui-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/VanillaTweaks_Colorful_Enchanting.zip"

[[files]]
file = "resourcepacks/VanillaTweaks_Lower_Shield.zip"

[[files]]
file = "resourcepacks/VanillaTweaks_What.zip"

[[files]]
file = "resourcepacks/bettervanillabuilding.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/bettervanillabuildingoverlays.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/bushybiomes.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/illuminated-shields.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/stefansarmorsnitems.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/stefansenchantedbooks.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
metafile = true
