hash-format = "sha256"

[[files]]
file = ".github/workflows/build.yml"

[[files]]
file = "config/bobby.conf"

[[files]]
file = "config/capes.json5"

[[files]]
file = "config/defaultoptions/keybindings.txt"

[[files]]
file = "config/defaultoptions/options.txt"

[[files]]
file = "config/roughlyenoughitems/config.json5"

[[files]]
file = "config/shulkerboxtooltip.json5"

[[files]]
file = "config/waila/waila.json"

[[files]]
file = "config/waila/waila_plugins.json"

[[files]]
file = "config/xaerominimap.txt"

[[files]]
file = "config/xaerominimap_entities.json"

[[files]]
file = "config/xaeropatreon.txt"

[[files]]
file = "config/xaeroworldmap.txt"

[[files]]
file = "config/zoomify.json"

[[files]]
file = "credits.txt"

[[files]]
file = "icon.png"

[[files]]
file = "mods.dot"

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
metafile = true

[[files]]
file = "mods/dashloader.pw.toml"
metafile = true

[[files]]
file = "mods/durabilityviewer.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-sound-filters.pw.toml"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
metafile = true

[[files]]
file = "mods/phosphor.pw.toml"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
metafile = true

[[files]]
file = "mods/quilt-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
metafile = true
