hash-format = "sha256"

[[files]]
file = ".github/workflows/build.yml"

[[files]]
file = "config/bobby.conf"

[[files]]
file = "config/capes.json5"

[[files]]
file = "config/defaultoptions/keybindings.txt"

[[files]]
file = "config/defaultoptions/options.txt"

[[files]]
file = "config/roughlyenoughitems/config.json5"

[[files]]
file = "config/shulkerboxtooltip.json5"

[[files]]
file = "config/waila/waila.json"

[[files]]
file = "config/waila/waila_plugins.json"

[[files]]
file = "config/xaerominimap.txt"

[[files]]
file = "config/xaerominimap_entities.json"

[[files]]
file = "config/xaeropatreon.txt"

[[files]]
file = "config/xaeroworldmap.txt"

[[files]]
file = "config/zoomify.json"

[[files]]
file = "credits.txt"

[[files]]
file = "icon.png"

[[files]]
file = "mods.dot"

[[files]]
file = "mods/CullLessLeaves-1.0.5.jar"

[[files]]
file = "mods/DynamicSoundFilters-1.3.0+1.19.jar"

[[files]]
file = "mods/PresenceFootsteps-1.6.1.jar"

[[files]]
file = "mods/XaerosWorldMap_1.26.6_Fabric_1.19.1.jar"

[[files]]
file = "mods/Xaeros_Minimap_22.13.2_Fabric_1.19.1.jar"

[[files]]
file = "mods/appleskin-fabric-mc1.19-2.4.1.jar"

[[files]]
file = "mods/badpackets-fabric-0.2.0.jar"

[[files]]
file = "mods/dashloader-4.1.2+1.19.jar"

[[files]]
file = "mods/durabilityviewer-1.19.1-fabric0.58.5-1.10.3.jar"

[[files]]
file = "mods/dynamiccrosshair-3.5.1+1.19.jar"

[[files]]
file = "mods/indium-1.0.8+mc1.19.2.jar"

[[files]]
file = "mods/iris-mc1.19.2-1.2.7.jar"

[[files]]
file = "mods/lambdabettergrass-1.3.0+1.19.jar"

[[files]]
file = "mods/lithium-fabric-mc1.19.2-0.8.3.jar"

[[files]]
file = "mods/modmenu-4.0.6.jar"

[[files]]
file = "mods/ok_zoomer-5.0.0-beta.9+1.19.jar"

[[files]]
file = "mods/phosphor-fabric-mc1.19.x-0.8.1.jar"

[[files]]
file = "mods/qfapi-4.0.0-beta.9_qsl-3.0.0-beta.14_fapi-0.60.0_mc-1.19.2.jar"

[[files]]
file = "mods/quilt_loading_screen-4.0.0+1.19.jar"

[[files]]
file = "mods/sodium-fabric-mc1.19.2-0.4.3+build.17.jar"

[[files]]
file = "mods/wthit-quilt-5.11.3.jar"

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
metafile = true
