hash-format = "sha256"

[[files]]
file = ".github/workflows/build.yml"

[[files]]
file = "config/bobby.conf"

[[files]]
file = "config/capes.json5"

[[files]]
file = "config/defaultoptions/keybindings.txt"

[[files]]
file = "config/defaultoptions/options.txt"

[[files]]
file = "config/roughlyenoughitems/config.json5"

[[files]]
file = "config/shulkerboxtooltip.json5"

[[files]]
file = "config/waila/waila.json"

[[files]]
file = "config/waila/waila_plugins.json"

[[files]]
file = "config/xaerominimap.txt"

[[files]]
file = "config/xaerominimap_entities.json"

[[files]]
file = "config/xaeropatreon.txt"

[[files]]
file = "config/xaeroworldmap.txt"

[[files]]
file = "config/zoomify.json"

[[files]]
file = "credits.txt"

[[files]]
file = "icon.png"

[[files]]
file = "mods.dot"

[[files]]
file = "mods/InGameAccountSwitcher-Fabric-1.18-7.1.3.jar"

[[files]]
file = "mods/RoughlyEnoughItems-7.0.346.jar"

[[files]]
file = "mods/architectury-3.2.47.jar"

[[files]]
file = "mods/cloth-config-6.0.45-fabric.jar"

[[files]]
file = "mods/dynamic-fps-2.0.6.jar"

[[files]]
file = "mods/fabric-api-0.43.1+1.18.jar"

[[files]]
file = "mods/optifabric-1.12.7.jar"

[[files]]
file = "mods/preview_OptiFine_1.18_HD_U_H3_pre7.jar"

[[files]]
file = "mods/worldedit-mod-7.2.8.jar"

[[files]]
file = "mods/wthit-fabric-4.3.1.jar"

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
metafile = true
