hash-format = "sha256"

[[files]]
file = ".github/workflows/build.yml"

[[files]]
file = "config/bobby.conf"

[[files]]
file = "config/capes.json5"

[[files]]
file = "config/defaultoptions/keybindings.txt"

[[files]]
file = "config/defaultoptions/options.txt"

[[files]]
file = "config/roughlyenoughitems/config.json5"

[[files]]
file = "config/shulkerboxtooltip.json5"

[[files]]
file = "config/waila/waila.json"

[[files]]
file = "config/waila/waila_plugins.json"

[[files]]
file = "config/xaerominimap.txt"

[[files]]
file = "config/xaerominimap_entities.json"

[[files]]
file = "config/xaeropatreon.txt"

[[files]]
file = "config/xaeroworldmap.txt"

[[files]]
file = "config/zoomify.json"

[[files]]
file = "credits.txt"

[[files]]
file = "icon.png"

[[files]]
file = "mods.dot"

[[files]]
file = "mods/DCCH-2.0+1.17.jar"

[[files]]
file = "mods/DynamicSoundFilters-1.3.0+1.18.2.jar"

[[files]]
file = "mods/OptiFine_1.18.2_HD_U_H7.jar"

[[files]]
file = "mods/PresenceFootsteps-1.5.0.jar"

[[files]]
file = "mods/RoughlyEnoughItems-8.1.449.jar"

[[files]]
file = "mods/SimpleRPC-fabric-1.18.2-3.0.0.jar"

[[files]]
file = "mods/XaerosWorldMap_1.20.7_Fabric_1.18.2.jar"

[[files]]
file = "mods/Xaeros_Minimap_22.6.1_Fabric_1.18.2.jar"

[[files]]
file = "mods/appleskin-fabric-mc1.18.2-2.4.0.jar"

[[files]]
file = "mods/architectury-4.2.50.jar"

[[files]]
file = "mods/charmonium-fabric-1.18-4.0.0.jar"

[[files]]
file = "mods/cloth-config-6.2.57-fabric.jar"

[[files]]
file = "mods/entityculling-fabric-mc1.18-1.5.1.jar"

[[files]]
file = "mods/fabric-api-0.51.1+1.18.2.jar"

[[files]]
file = "mods/ferritecore-4.2.1-fabric.jar"

[[files]]
file = "mods/lazydfu-0.1.2.jar"

[[files]]
file = "mods/modmenu-3.1.1.jar"

[[files]]
file = "mods/notenoughcrashes-4.1.6+1.18.2-fabric.jar"

[[files]]
file = "mods/optifabric-1.13.0.jar"

[[files]]
file = "mods/pinglist-1.3.3.jar"

[[files]]
file = "mods/seamless-loading-screen-1.4.0+1.18.2.jar"

[[files]]
file = "mods/wthit-fabric-4.8.1.jar"

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
metafile = true
