name = "Evan's Pack"
author = "Evan Pratten"
version = "snapshot-24w05a-r1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.15.6"
minecraft = "24w05a"

[options]
acceptable-game-versions = ["1.20.3", "1.20.4"]
no-internal-hashes = true
