name = "Evan's Pack"
author = "Evan Pratten"
version = "1.16.4r1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.10.7"
minecraft = "1.16.4"

[options]
acceptable-game-versions = ["1.16.2", "1.16.3", "1.16.4"]
no-internal-hashes = true
