name = "Evan's Pack"
author = "Evan Pratten"
version = "1.21.1r1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
no-internal-hashes = true
