name = "Evan's Pack"
author = "Evan Pratten"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b74333ec44e1ee3c1fb414c1b7be746710f9440db41d36be05c110c611b57e6"

[versions]
minecraft = "1.19.4"
quilt = "0.18.9"

[options]
acceptable-game-versions = ["1.19.3"]
