name = "Evan's Pack"
author = "Evan Pratten"
version = "0.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
minecraft = "1.20.1"
quilt = "0.19.0"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
no-internal-hashes = true
