name = "Evan's Pack"
author = "Evan Pratten"
version = "0.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
minecraft = "1.20"
quilt = "0.18.10"

[options]
acceptable-game-versions = ["1.20"]
no-internal-hashes = true
